### ISSUE TITLE
Support for mentions that start with a symbol? (e.g. @_user)

### ISSUE THREAD

**Issue by L4grange** [linkedin/Spyglass#107]
I would like to thank you for this library, it has helped us speed up developing our mentions list a lot!
On our platform we have valid usernames that can start with an underscore `_` or a period `.`.

I did find out that the `isValidMention` method in `WordTokenizer.java` contains the following code:
```
// If input has length greater than one, the second character must be a letter or digit
// Return true if and only if second character is a letter or digit, i.e. "@d"
return Character.isLetterOrDigit(token.charAt(1));
```
If we returned true instead of checking if `isLetterOrDigit` we could solve our problem. Is that something this library is planning to support? We are planning on creating our own for with our required changes, let me know if this is something you want added into the library to open a PR, or if there is already a way to achieve this that we missed.

**Comment by nhibner** [comment]
Thanks, glad that you're finding this library useful.

From the library's standpoint, it is hard for us to support tokenization logic generally, as every app has different needs. The library provides WordTokenizer as an attempt to handle common use cases. If using WordTokenizer directly does not fit your use case, there are a couple of other options:

- Subclass WordTokenizer, overriding the methods you need to customize.
- Implement the Tokenizer interface yourself, which gives you the most freedom.

I am open to changing the library if there is something the library can provide that will make things easier for multiple use cases. However, I'd also like to avoid changing the library for a single use case if there are other solutions available.

**Comment by L4grange** [comment]
Thank you for your reply!
How can I subclass WordTokenizer, to override the `isValidMention` method, since the `mConfig` property is private to the parent class, so I can't access the `THRESHOLD` parameter?

**Comment by nhibner** [comment]
You have access to the WordTokenizerConfig in the constructor of your subclass, so you can do something like:
```
public class MyWordTokenizer extends WordTokenizer {

    @NonNull private final WordTokenizerConfig config;

    public MyWordTokenizer(@NonNull WordTokenizer config) {
        super(config);
        this.config = config;
    }

    @Override
    public boolean isValidMention(..) {
        // Custom code here, reference this.config as needed
    }
```

**Comment by L4grange** [comment]
Thank you for pointing us to the right direction!
We've managed to achieve our desired result using your suggestion 😃
