### ISSUE TITLE
No TokenReceiver callback if a special character is followed by explicit char

### ISSUE THREAD

**Issue by zoubarry** [linkedin/Spyglass#111]
For example, if we use "@" as explicit char for at mention
"@abc" will work as expected to callback on tokenReceiver
However,  a special char won't work e.g. "@*", no token receiver callback is triggered

**Comment by nhibner** [comment]
This is expected -- the default tokenizer for mentions does not allow for special characters in the mention, only letters and digits. If your use case requires that, you will need to provide either a custom WordTokenizerConfig or your own implementation of the Tokenizer interface. 

In general, Spyglass tries to provide intelligent default behavior that works for as many use cases as possible. When more specific behavior is needed, Spyglass also exposes extension points (via configs and interfaces) to allow for deep customization.
