### ISSUE TITLE
How To Keep Keyboard Open While Scrolling Suggestion List

### ISSUE THREAD

**Issue by jschleppy** [linkedin/Spyglass#121]
I run the sample code, and that works as expected, where the keyboard will remain open while I scroll around the suggestions list.

What I can't make sense of is why in my own app, simply touching outside of the MentionsEditText field closes the keyboard. Would anyone here happen to have any suggestions to look into regarding this behavior difference?

**Comment by nhibner** [comment]
It's kind of hard to give good suggestions without having more context, but for what it's worth, try setting these values on the MentionsEditText in XML:

```java
<com.linkedin.android.spyglass.ui.MentionsEditText
        ...
        android:imeOptions="flagNoExtractUi"
        android:focusable="true"
        android:focusableInTouchMode="true"/>
```

The sample app uses those setting. Hopefully one of those helps!
