### ISSUE TITLE
Problem making the suggestions_list to show above the MentionsEditText

### ISSUE THREAD

**Issue by peakandroid** [linkedin/Spyglass#127]
I am trying to display the list above the edit text to show suggestions similar to whatsapp. Is it possible to add our own custom layout

**Comment by nhibner** [comment]
Yes, this is described in the README in the "Usage" section [here](https://github.com/linkedin/Spyglass/#usage). You'll want to use the `MentionsEditText`, which gives you full control over where and how the list is displayed. The `GridMentions` example in the sample app also demonstrates this ([code](https://github.com/linkedin/Spyglass/blob/main/spyglass-sample/src/main/java/com/linkedin/android/spyglass/sample/samples/GridMentions.java)).
