### ISSUE TITLE
How to use it with jetpack compose ?

### ISSUE THREAD

**Issue by anthony-fresneau-kiplin** [linkedin/Spyglass#136]
Is there a sample to use MentionsEditText in jetpack compose ?

**Comment by nhibner** [comment]
Sorry, there are no samples for using this with Jetpack Compose. This library was created a long time before Jetpack Compose existed and is essentially in maintenance mode. You may still be able to use it in Jetpack Compose via the interop functionality (described [here](https://developer.android.com/develop/ui/compose/migrate/interoperability-apis/views-in-compose)). If someone would like to post a PR to add a sample to demonstrate this, please don't hesitate, I agree it would be good to have.
