### ISSUE TITLE
Suggestible.getId() conflicts with everything

### ISSUE THREAD

**Issue by bpappin** [linkedin/Spyglass#19]
Any bean that has an ID has a getId method, but its not always an int return type (in fact in modern code, it's seldom an int).

This should be changed to differentiate it from a POJO's id.

```java
Suggestible.getSuggestibleId();
```

While your at it, the ```String getPrimaryText();``` method is too generic. maybe rename it to ```getSuggestiblePrimaryText()```;.

As for right now, I'm looking for a workaround for this little showstopper.
I don't mind fixing it and generating a pull request if that will help.

**Comment by nhibner** [comment]
I agree with you, these are valid points. If you would like to submit a pull request with the fixes, I'll accept it and release a new version within a couple of days.

**Comment by nhibner** [comment]
The code looks good, but can you please fix the TestMention class (which appears to be why the tests failed)?
