### ISSUE TITLE
Editing feature

### ISSUE THREAD

**Issue by andhie** [linkedin/Spyglass#26]
Is there a way to manually create Mentions? 
This is to cater to editing existing post/status updates. Based on the current sample implementations, its only for creating a non-editable status. 
In order to edit, there should be some sort of way to notify a range of text is a Mention and convert it accordingly

**Comment by nhibner** [comment]
Can you please provide a few more details on what your exact use case is?

**Comment by andhie** [comment]
As i checked the LinkedIn app, after you posted a status update, you cannot edit it again. unless you delete it and re-post.
My extra use case is the ability to edit existing status. that would mean i need to `setText` the original text and then notify MentionEditText which part of the text is a Mention

**Comment by nhibner** [comment]
Mentions are just spans placed within the text. To get the original text with the mentions, you can just call `getText` on the MentionEditText. Then, you can assign the text back to the MentionEditText via `setText`, and it will use whatever spans that were in that text. There is no need to manually notify the MentionEditText where the original mentions were, as all mentions are saved within the text itself.

**Comment by andhie** [comment]
Great, tested and works. thanks for pointing me the right direction

**Comment by nhibner** [comment]
No problem, glad to be of help :)

**Comment by amitmcn** [comment]
Hi Sir,
           Please help me how edit.

**Comment by nhibner** [comment]
@amitmcn replied to you on the issue you opened: #45 :)
