### ISSUE TITLE
Turn off "implicit" mentions

### ISSUE THREAD

**Issue by Shahroz16** [linkedin/Spyglass#27]
Hey, me again :D

This is my "Tokenizer" configuration 
WordTokenizerConfig config = new WordTokenizerConfig.Builder().setThreshold(2).setMaxNumKeywords(100).build();

I just want to see suggestions when "@" is entered. But whenever 2 characters are entered suggestions starts showing. "setThreshold(2)" is because I want to cater space " " in between text while searching. For example, "A M". 
Let me know if this makes sense, otherwise I will try to explain further.

Thanks, 
Shahroz

**Comment by nhibner** [comment]
Hi Shahroz,

Let me elaborate a little further on the parameters you mentioned so we're on the same page:

**setMaxNumKeywords(int x)**
- the maximum number of words that can be returned in a query token by a given tokenizer
- note that the query token is used to generate the list of mentions (this does not limit the number of words in your mentions, only the number of words you'll have to query)

**setThreshold(int x)**
- this threshold refers to the number of characters needed in a word before the tokenizer will generate tokens for that word

You'll need to make sure these parameters are set according to your requirements. For example, consider the string `Grand Canyon`. If the user types `@Grand Can`, you would need to have the max number of keywords to be at least 2. The threshold would need to be no more than 3 (as the user typed 3 characters in the current word).

You'll need to consider your desired behavior and adjust these parameters accordingly. Note that adjusting these parameters just determines when a query token will be created and what it can contain. You can adjust the parameters to be more lenient (i.e. set the max number of keywords to Integer.MAX  and the threshold to 0). Doing so will generate a lot more query tokens, but you can always choose to ignore any implicit tokens (i.e. return no results).

You're also welcome to implement your own tokenizer if the one provided does not suit your needs. The WordTokenizer is meant to be for general use, but a tokenizer for just explicit tokens would be a lot easier to implement. If you do this, please send me a pull request and we can add it to the library for others with similar use cases.

**Comment by Shahroz16** [comment]
Sorry for late response, have been very busy with work lately, The moment I will get a second to breathe, I will send you a pull request. Thanks for this amazing library again.
