### ISSUE TITLE
 Get string in a form that I can send off to the server

### ISSUE THREAD

**Issue by jdoes** [linkedin/Spyglass#28]
Hey there, thanks for this amazing library, i am facing some issues. 

I need to obtain the text in a format that I can send it to the server. Something like this:

user text with mentions :   "I want to thanks to @John and to @Jane "

server text: "I want to thanks to  [John, id:45] and to [Jane, id:156]"

How I could achieve this ? 
Thanks.

**Comment by nhibner** [comment]
Hi @jdoes,

Since everyone requires different formats for sending these annotated strings to their servers, there is no standard method in the library to do exactly what you want. Rather, you will need to build the data structure that you will send to the server yourself. You might be able to do something like this (note: this is rough code, haven't tested it):

```java
MentionsEditable text = mentionsEditText.getMentionsText();
List<MentionSpan> mentionSpans = text.getMentionSpans();
for (MentionSpan span : mentionSpans) {
    int start = text.getSpanStart(span);
    int end = text.getSpanEnd(span);
    String currentText = text.getSubsequence(start, end).toString();
    text.replace(start, end, "[" + currentText + ", id:" + span.getId() + "]");
}
```

Hope that at least points you in the right direction!

**Comment by jdoes** [comment]
Thanks @nhibner !!!!!

I'm doing something similar but using getTextForDisplayMode

@Override
public String getTextForDisplayMode(MentionDisplayMode mode) {
 switch (mode) {
...
            case NONE:
                return "@[" + getFirstName() + "](999) ";
           ...
        }
    }

**Comment by jdoes** [comment]
Thanks @nhibner , I was doing something similar.

**Comment by ahmedsaber00** [comment]
where exactly should i write this ?

**Comment by ahmedsaber00** [comment]
and how to make span.getId() return the tagged user id ?

**Comment by robchava** [comment]
@ahmedsaber00 Maybe extend the `Mention` class to include custom data, and then extract that in the for loop.

**Comment by lucandr** [comment]
@nhibner I can't make this code working:
```
MentionsEditable text = mentionsEditText.getMentionsText();
List<MentionSpan> mentionSpans = text.getMentionSpans();
for (MentionSpan span : mentionSpans) {
    int start = text.getSpanStart(span);
    int end = text.getSpanEnd(span);
    String currentText = text.getSubsequence(start, end).toString();
    text.replace(start, end, "[" + currentText + ", id:" + span.getId() + "]");
}
```

How can I replace span strings so I can send the String encoded to the server?

Thanks for your time!

**Comment by lucandr** [comment]
@analleraP   did u make it working?

**Comment by NischalManandhar** [comment]
You can make copy of `mentionsEditText.getMentionsText()` and have the `replace` method working.

    MentionsEditable text = MentionsEditable(mentionsEditText.getMentionsText());
    List<MentionSpan> mentionSpans = text.getMentionSpans();
    for (MentionSpan span : mentionSpans) {
        int start = text.getSpanStart(span);
        int end = text.getSpanEnd(span);
        String currentText = text.subSequence(start, end).toString();
        text.replace(start, end, "[" + currentText + ", id:" + span.mention.getSuggestibleId() + "]");
    }
