### ISSUE TITLE
Space double functionality

### ISSUE THREAD

**Issue by emce** [linkedin/Spyglass#33]
Is there a way to use space as word breaker and as a part of query, for example by pasting `John Wi` allowing to search John Wick, John Witwicky, etc.

**Comment by nhibner** [comment]
Yes, if you're using the `WordTokenizer`, call `setMaxNumKeywords(x)` to define how many words you would like to receive for your query. So for example, when you call `setMaxNumKeywords(2)`, you will receive queries containing the current word and the previous word (unless the user has only typed one word). This means that typing `Alpha Bravo Charl` would give you `Bravo Charl` as the query token for which you would need to return the search results.

**Comment by emce** [comment]
This is my config: 
```
WordTokenizerConfig tokenizerConfig = new WordTokenizerConfig.Builder()
        .setMaxNumKeywords(1)
        .setThreshold(3)
        .setExplicitChars("@")
        .setWordBreakChars(" ." + System.getProperty("line.separator"))
        .build();
```
and with this I am not able to put another mention, for example, I'm putting `John` and choosing John Wick, but after putting another `@` I'm not getting next token (list is not being triggered to show)

**Comment by nhibner** [comment]
Did you try putting `setMaxNumKeywords(2)`? Also, for `@` to trigger another list, it needs to have a word-breaking character in front of it (otherwise, it's considered to be part of the previous word by default).
