### ISSUE TITLE
Calling `insertMention` results in strange editable text

### ISSUE THREAD

**Issue by mako-taco** [linkedin/Spyglass#37]
1. Set up a tokenizer with maxKeywords = 2, no explicit characters
2. Type two keywords
3. Call insertMention on a valid suggestion for the keywords

Expected:
Both keywords are removed, and replaced with the mention

Actual:
Only the second keyword is replaced with a mention, the first keyword remains

There appears to be code in `insertMention` which changes the (correct) start index for implicit mentions with multiple keywords here: https://github.com/linkedin/Spyglass/blob/7da824a7ae4324c6eb33668ea879131fd8f43cf1/spyglass/src/main/java/com/linkedin/android/spyglass/ui/MentionsEditText.java#L759

**Comment by mako-taco** [comment]
If I write a PR will you guys consider merging? Don't want to waste my time submitting if this project isn't maintained anymore.

**Comment by nhibner** [comment]
Sure, we'd be glad to consider merging any PRs.
