### ISSUE TITLE
Mention Click Listener

### ISSUE THREAD

**Issue by AladdinHZ** [linkedin/Spyglass#42]
Hello Guys, Great job so far .
Please I was wondering if their is any way to add on mention click listener to MentionEditText ?

**Comment by nhibner** [comment]
What's your use case? By default, clicking a mention toggles the selected state. If you need to customize the behavior when a mention is clicked, you can provide your own subclass of `MentionSpan` by setting a `MentionSpanFactory` on `MentionsEditText`.
