### ISSUE TITLE
Insert text before the first mention is not possible

### ISSUE THREAD

**Issue by anthony3444** [linkedin/Spyglass#44]
Hi there!

I've tested your sample, and specifically GridMentions; if I add at the beginning a mention, then after I can't insert anytext before it. It's not possible to move the cursor at the beginning of text.

Ps : it's with **MentionsEditText**

<img width="432" alt="sans titre" src="https://cloud.githubusercontent.com/assets/18351826/21494541/90a3d25a-cc12-11e6-831d-e5d393546230.png">

Thank you very much for your help!

**Comment by RahulSDeshpande** [comment]
Hey @anthony3444 there are two ways to do it:

1) You can manually move the cursor at the beginning of the mention by finger touch, & its possible :)
2) Implement ```MentionsEditText.MentionWatcher```, override its callback methods & do ```        commentEditText.setSelection(0);``` like below:
```java
..
commentEditText.addMentionWatcher(new MentionsEditText.MentionWatcher() {
    @Override
    public void onMentionAdded(@NonNull Mentionable mention, @NonNull String text, int start, int end) {
        commentEditText.setSelection(0);
    }

    @Override
    public void onMentionDeleted(@NonNull Mentionable mention, @NonNull String text, int start, int end) {
    }

    @Override
    public void onMentionPartiallyDeleted(@NonNull Mentionable mention, @NonNull String text, int start, int end) {
    }
});
..
```
