### ISSUE TITLE
Insert text and mention in richeditorview

### ISSUE THREAD

**Issue by amitmcn** [linkedin/Spyglass#45]
Hi Sir,
          I want to set text combined with text and mention in RichEditorView. 
eg-good morning **Amit** and **Dinesh**
  here Amit and Dinesh are mentionable.
comment_discription.setText("good morning **Amit** and **Dinesh**");

**Comment by nhibner** [comment]
You'll need to set a `MentionSpan` at the necessary locations in the text. For example:
```java
SpannableStringBuilder text = new SpannableStringBuilder("good morning Amit and Dinesh");
text.setSpan(new MentionSpan(amitMention), 13, 17, Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);
text.setSpan(new MentionSpan(dineshMention), 22, 28, Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);
comment_description.setText(text);
```
Note that this code is not really specific to the library. Android allows apps to control how text is rendered by adding spans over specific indices in the text. The library renders mentions by using its own `MentionSpan` class.

**Comment by vivekdhumal** [comment]
I also had a same scenario in my case the custom mention text color is changing to default when I apply the mention span. 
I'm using the mention span config as follow
```java
MentionSpanConfig.Builder builder = new MentionSpanConfig.Builder();
builder.setMentionTextColor(context.getResources().getColor(R.color.colorPrimaryDark));
MentionSpanConfig mentionSpanConfig = builder.build();
editorView.setMentionSpanConfig(mentionSpanConfig);
```

**Comment by Vaibhav2002** [comment]
@vivekdhumal were you able to solve this ?
