### ISSUE TITLE
How to set Explicit Character?

### ISSUE THREAD

**Issue by farazappy** [linkedin/Spyglass#46]
Hello, Currently I am using `WordTokenizer` with `MentionsEditText` as showed in `GridMentions` Sample!
This is my config : 
`private WordTokenizerConfig tokenizerConfig = new WordTokenizerConfig.Builder().setMaxNumKeywords(3).setThreshold(3).build();`

Problem is that this triggers the `OnQueryReceived` and looks for suggestions on any random text input but I want that to be triggered only when the user uses **@** keyword. 

This currently works like this ->
**User Input:** _I went **(Query Is Triggered)** on a dinner_ 

What I want -> 
**User Input:** _I went on a dinner with **@Faraz (Here I want the query to be triggered and show suggestions)**_

**Comment by nhibner** [comment]
If you want a quick way to only allow explicit mentions, you can configure the `WordTokenizer` with a large threshold. This configuration should work:
```
new WordTokenizerConfig
            .Builder()
            .setWordBreakChars(", ")
            .setExplicitChars("@")
            .setThreshold(Integer.MAX_VALUE)
            .build();
```

**Comment by farazappy** [comment]
@nhibner How can I get only the mentions from the editor? Like I am saving the whole `.getText()` in my database but this will save the mentions as normal text and later render it as normal text, so can I get only the mentions, save it in database and retrieve it later?

**Comment by nhibner** [comment]
@farazappy You can call `getText().getMentionSpans()` to get a list of the mentions in the text. For more help on saving/restoring these mentions from a database, see the discussions on #35

**Comment by farazappy** [comment]
@nhibner Thanks! Really helpful! Why don't you guys create a custom `TextView` like the `EditText` which has the `insertMentions()` methods to insert the mentions easily while rendering! 😃

**Comment by irfaan008** [comment]
@farazappy I have done this using below code. This renders the mention in highlighted way

```
public Spannable getText() {
        Pattern pattern = Pattern.compile("(@\\w+)");
        Matcher matcher = pattern.matcher(text);
        List<BoPeople> mentions = new ArrayList<>();
        while (matcher.find()) {
            String g1 = matcher.group(1);
            mentions.add(new BoPeople(matcher.group(), matcher.start(), matcher.end()));
        }
        Spannable spannable = new SpannableString(text);
        if (mentions.size() > 0)
            for (BoPeople m : mentions) {
                spannable.setSpan(
                        new ForegroundColorSpan(Color.BLUE),
                        m.getStart(), m.getEnd(),
                        Spannable.SPAN_EXCLUSIVE_EXCLUSIVE);
            }
        return spannable;
    }
```
