### ISSUE TITLE
Not able to use  setTextColor and setHintColor 

### ISSUE THREAD

**Issue by shashankpsingh** [linkedin/Spyglass#47]
Hey,
I can't find basic feature i.e setTextColor and set HintColor for text and hint used in RichEditorView.
Please mention any update regarding this.

**Comment by nhibner** [comment]
Hello,

The general recommendation is to use the `MentionsEditText` for doing more extensive customization. There are examples of this in the sample app.

Granted, setting text and hint color is a pretty basic customization. If you'd like to send a pull request with that functionality, I'll merge it in.

**Comment by shashank26ashu** [comment]
Sure, will update when I am done with the functionality.
