### ISSUE TITLE
Adding space in front of Mention behave weird ?

### ISSUE THREAD

**Issue by bbincybbaby** [linkedin/Spyglass#48]
Adding space in front of mention behaving weirdly

**Comment by deepaksingalkiwitech** [comment]
Looks like there is some issue with replace(..) method in MentionsEditable class.

**Comment by bbincybbaby** [comment]
yup that i know. But i can't understand what is real issue

**Comment by RahulSDeshpande** [comment]
Hey guys, the issue is that you are inserting a space at the end of the mentioned text, will surely trigger TextWatcher listener's beforeTextChanged(), onTextChanged() & afterTextChanged() for your EditText.

You need to have your logic to bypass these listeners to make it non-weird :)
