### ISSUE TITLE
Save state of the mention edit text.

### ISSUE THREAD

**Issue by shafayatb** [linkedin/Spyglass#55]
Hi I am having an issue with saving the state of the mention edit text.

I am tagging some users in the mention edit text in an activity and closing the activity. Now returning to the activity and checking what users I have tagged in the mention edit text. But I cannot seem to set the users in my mention edit text again. The following is what I have tried,

                       `for (User user : userList) {
                            eTxtTag.insertMention(user);
                             eTxtTag.setText(user.getUserName()+ " " + eTxtTag.getText());
                              //int ei = user.getUserName().length();
                              //Selection.setSelection(eTxtTag.getText(), ei);
                    }` 

Here the user is my mentionable object and the userlist is the list of mention users. So how can I fix the issue.

**Comment by RahulSDeshpande** [comment]
Please refer #35 👍
