### ISSUE TITLE
Can't input aaxaa  (chinese input method)

### ISSUE THREAD

**Issue by richmonkey** [linkedin/Spyglass#63]
1. input aax
2.input "aa" one time.

MentionsEditable.replace is the problem.
// On certain software keyboards, the editor appears to append a word minus the last character when it is really
// trying to just delete the last character. Until we can figure out the root cause of this issue, the following
// code remaps this situation to do a proper delete.

Need find the root cause.

**Comment by nhibner** [comment]
Realized that there's a newer issue for this already, so will close this as a duplicate. For the latest, see https://github.com/linkedin/Spyglass/issues/105
