### ISSUE TITLE
How to set mentions on MentionEditText from string?

### ISSUE THREAD

**Issue by yogshinde** [linkedin/Spyglass#65]
I have a string with mentions set on text view, I want to set those mentions while editing the text.

**Comment by nhibner** [comment]
It's not clear to me what you are asking. A "string with mentions" is just a spanned string containing MentionSpans. If you have a string with mentions, then you can just set it on the MentionsEditText via setText.

For reference, see the docs around spanned strings ([docs](https://developer.android.com/reference/android/text/Spanned)) and check out some guides on handling spans in text ([here](https://medium.com/google-developers/spantastic-text-styling-with-spans-17b0c16b4568)'s a good explanation).
