### ISSUE TITLE
android:singleLine="true" , is not available for spyglass

### ISSUE THREAD

**Issue by devrath** [linkedin/Spyglass#74]
`android:singleLine="true"`

This is not possible in Spyglass. Is this the limitation of this widget ?
My purpose is to Make spyglass act as android native EditText widget so that we can scroll horizontally and in a single line

**Comment by nhibner** [comment]
This is a limitation of the RichEditorView, which is a complex view layout that handles both text input and displaying suggestions for you.

If you would like to define your own UI for displaying suggestions, you can use the MentionsEditText directly and hook up your own RecyclerView for displaying suggestions (see the [GridMentions sample](https://github.com/linkedin/Spyglass/blob/master/spyglass-sample/src/main/java/com/linkedin/android/spyglass/sample/samples/GridMentions.java)). With this setup, you can configure the MentionsEditText as a normal, native EditText widget (which includes setting it to singleLine).
