### ISSUE TITLE
How to insert several mentions at the "same" time?

### ISSUE THREAD

**Issue by anthony3444** [linkedin/Spyglass#80]
Hi guys!

First at all thank you very much for this awesome library!

I have a "problem": I can't add several mentions at the same time. The first one is added (OK), but other nothing, because the EditableText is not yet update...

> // Add these mentions
>             for (Mentionable mention : mentions) {                     
>                 mDescriptionEditText.insertMention(mention);
>             }

If I add one by one it works, but in **a loop** only the first one is take account.

Could you help me please?

Thank you very much guys!

**Comment by nhibner** [comment]
The `insertMention(..)` function that you are calling is essentially a helper function to insert a mention at the current location of the cursor in the EditText. If you call that function in a loop, you will be inserting mentions over the same piece of text.

Please keep in mind that a mention is just a span applied over a section of text. You can create your own text and apply instances of `MentionSpan` on different sections of text (similar to how you would add a `BoldSpan` to bold text).

**Comment by anthony3444** [comment]
Hi @nhibner!

Thanks for your reply, but unfortunately I don't understand exactly what you mean. 
How can I listen the end of textview update (after my first `insertMention(...)` done) ?
