### ISSUE TITLE
Counter is Visible after using mentions

### ISSUE THREAD

**Issue by Inshaki** [linkedin/Spyglass#81]
After choosing one of the possible suggestions in the mentions, the visibility of the counterview is visible again after i have used initially this method 

composerMessageView.displayTextCounter(false)

But when the onReceiveSuggestionsResult(result, BUCKET) is been called for the second time, it changes the visibility

**Comment by nhibner** [comment]
Not sure if I follow. Can you please provide more information on how to reproduce this? A video or an example project would be ideal.

**Comment by Inshaki** [comment]
1 - My settings should not show the counter of the character
2 - Initially, the counter is not visible
3 - I start the mention view and displaySuggestions is called with display = true in RichEditorView.class
4 - I click at an item of in the mentionlist
5 - Again displaySuggestions gets called, however now the boolean of display = false
6 - Finally lineNumber 381 is called: mTextCounterView.setVisibility(View.VISIBLE);

I tried fixing this issue with a textwatcher and setting the visibility off myself. But that didnt work, because after clicking an item in the mentionlist the methods of the watcher do not get called

**Comment by nhibner** [comment]
Ah, I see what you mean. Thanks for the detailed description and pull request. I went ahead and merged the fix.
