### ISSUE TITLE
Spyglass with standard HTML tags

### ISSUE THREAD

**Issue by anthony3444** [linkedin/Spyglass#82]
Hi guys!

In my string I have mentions (OK) and HTML tags like bold and links. 

I use `setText(Html.fromHtml(text, null, null));` but it doesn't work properly when there are mix of mentions and HTML tags. Is there a simple way to do that? May I parse by myself all the HTML tags?

Thank you very much

**Comment by nhibner** [comment]
Mentions are just normal spans in a spanned string that can be manipulated via standard methods from the Android SDK. My best guess is that the `Html.fromHtml(..)` method does not work well when the input text contains arbitrary spans.
