### ISSUE TITLE
Add mention if not found

### ISSUE THREAD

**Issue by VitaliyShuba** [linkedin/Spyglass#85]
So here is my WordTokenizer 
`WordTokenizer(WordTokenizerConfig.Builder().setWordBreakChars(" ")
            .setExplicitChars("#").setMaxNumKeywords(1).setThreshold(2).build())`

Is there a way to add new mention automatically, when suggestions are not found and I press space (" " my word break).
So lets say I entered: "Spyglass", no suggestions are found, I entered space (" ") and this Spyglass became new Mention with "#" automatically added.

Sorry for a complicated explanation...

**Comment by nhibner** [comment]
One approach:  You could set a `TextWatcher` on the `MentionsEditText`. This will provide you with a callback every time the text is changed. From this logic, you could detect when the user enters a space, and if the previous word was not detected as a mention, you could make it one with a "#" automatically added. Note that none of this is specific to Spyglass however.
