### ISSUE TITLE
Support Multiple Tokenizers?

### ISSUE THREAD

**Issue by atominvention** [linkedin/Spyglass#89]
Is there a way to define multiple tokenizers?
I would like to use "@" to query a list of users and "#" to query a list of hash tags

**Comment by nhibner** [comment]
Tokenizer is a generic interface. You can implement it however you want.

If all you want is to support multiple explicit characters, you can can set multiple explicit characters in the `WordTokenizerConfig` by passing in a string like "@#". Then, in your implementation of a `QueryTokenReceiver`, the `QueryToken` you are given in the callback will indicate if the explicit character is either a "@" or a "#".
