### ISSUE TITLE
java.lang.ClassCastException : android.text.SpannableStringBuilder cannot be cast to com.linkedin.android.spyglass.mentions.MentionsEditable

### ISSUE THREAD

**Issue by breakwhile** [linkedin/Spyglass#93]
Hi guys, we have an exception in our app:
java.lang.ClassCastException: android.text.SpannableStringBuilder cannot be cast to com.linkedin.android.spyglass.mentions.MentionsEditable
com.linkedin.android.spyglass.ui.MentionsEditText.getMentionsText() (MentionsEditText.java : 1300)
The above is abnormal information, Can you solve this problem?

**Comment by nhibner** [comment]
Resolved this in https://github.com/linkedin/Spyglass/commit/5a31d822c2bda3742f23867d523cef1bc11df5ae, available in version 2.1.0
